name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  # sync:
  #   uses: ./.github/workflows/sync.yml
  #   secrets: inherit

  package:
    uses: ./.github/workflows/package.yml

  # release:
  #   uses: ./.github/workflows/release.yml
  #   needs: package